test_community/ai/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('learnedgesture/', views.learned_model_gesture),
    path('gesture/', views.gesture_register),
    path('authentication/', views.authentication_model_gesture ),
    path('initmonitor/', views.Initdetectme ),
    path('learnedmonitor/', views.learneddetectme ),
    path('learningmonitor/', views.learningdetectme ),
    path('authenticationmonitor/', views.authenticationdetectme ),
]

test_community/board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('detail/<int:pk>/', views.board_detail),
    path('detail/<int:pk>/delete/', views.board_delete),
    path('detail/<int:pk>/update/', views.board_update),
    path('list/', views.board_list),
    path('write/', views.board_write)
]

test_community/test_community/urls.py
from django.contrib import admin
from django.urls import path, include
from fcuser.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('fcuser/', include('fcuser.urls')),
    path('', home),
    path('ai/', include('ai.urls')),
]

test_community/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=128,
                             verbose_name='제목')
    writecontents = models.TextField(verbose_name='내용')
    writer = models.ForeignKey('fcuser.Fcuser', on_delete=models.CASCADE,
                               verbose_name='작성자')
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'board'
        verbose_name = '게시글'
        verbose_name_plural = '게시글'

test_community/board/forms.py
from django import forms

class BoardForm(forms.Form):
    title = forms.CharField(
        error_messages={
            'required': '제목을 입력해주세요.'
        },
        max_length=128, label="제목")
    writecontents = forms.CharField(
        error_messages={
            'required': '내용을 입력해주세요.'
        },
        widget=forms.Textarea, label="내용")

test_community/board/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import Http404
from fcuser.models import Fcuser
from .models import Board
from .forms import BoardForm

# Create your views here.


def board_detail(request, pk):
    if not request.session.get('user'):
        return redirect('/fcuser/login/')

    pk = int(pk)
    try:
        board = Board.objects.get(pk=pk)
    except Board.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다')

    if board.writer_id == request.session.get('user'):
        context = True
    else:
        context = False

    return render(request, 'board_detail.html', {'board': board, 'writer': context})


def board_write(request):
    if not request.session.get('user'):
        return redirect('/fcuser/login/')

    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            user_id = request.session.get('user')
            fcuser = Fcuser.objects.get(pk=user_id)

            board = Board()
            title = form.cleaned_data['title']
            board.title = str(title)
            writecontents = form.cleaned_data['writecontents']
            board.writecontents = str(writecontents)
            board.writer = fcuser
            board.save()

            return redirect('/board/list/')
    else:
        form = BoardForm()

    return render(request, 'board_write.html', {'form': form})


def board_list(request):
    if not request.session.get('user'):
        return redirect('/fcuser/login/')

    all_boards = Board.objects.all().order_by('-id')
    page = int(request.GET.get('p', 1))
    paginator = Paginator(all_boards, 3)

    boards = paginator.get_page(page)
    return render(request, 'board_list.html', {'boards': boards})


def board_delete(request, pk):
    user = request.session.get('user')
    board = Board.objects.get(pk=pk)

    if request.method == 'GET':
        if board.writer_id == user:
            board.delete()
            return redirect('/board/list')
    else:
        return redirect('/board/detail/')


def board_update(request, pk):
    board = Board.objects.get(pk=pk)

    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = Board.objects.get(pk=pk)
            board.title = str(form.cleaned_data['title'])
            writecontents = form.cleaned_data['writecontents']
            board.writecontents = str(writecontents)
            board.save()

        return redirect('/board/list')

    else:
        form = BoardForm()

    return render(request, 'board_write.html', {'form': form})

test_community/board/templates/base.html
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="refresh" content="1800">

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" /> -->
  <link rel="stylesheet" href="/static/bootstrap.min.css" />
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  {% block header %}
  {% endblock %}
</head>

<body>
  <div class="container">
    {% block contents %}
    {% endblock %}
  </div>
</body>

</html>

test_community/board/templates/board_detail.html
{% extends "base.html" %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <div class="card" style="width: 100%;">
      <div class="card-body">
        <h5 class="card-title">제목 : {{ board.title }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ board.writecontents|safe }}</li>
      </ul>
    </div>
    {% if writer %}
    <button type="button" class="btn btn-primary"
      onclick="location.href='/board/detail/{{ board.id }}/delete'">삭제하기</button>
    <button type="button" class="btn btn-primary"
      onclick="location.href='/board/detail/{{ board.id }}/update'">수정하기</button>
    {% endif %}
    <button class="btn btn-primary" onclick="location.href='/board/list/'">돌아가기</button>
  </div>
</div>
{% endblock %}

test_community/board/templates/board_list.html
{% extends "base.html" %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>인증파 Q&A</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-3">
    <button class="btn btn-primary btn-block" onclick="location.href='/ai/gesture/'">손 제스처 등록</button>
  </div>
  <div class="col-3">
    <button class="btn btn-primary btn-block" onclick="location.href='/ai/authentication/'">손 제스처 인증</button>
  </div>
  <div class="col-3">
    <button class="btn btn-primary btn-block" onclick="location.href='/ai/learnedgesture/'">손 제스처 제어</button>
  </div>
  <div class="col-3">
    <button class="btn btn-primary btn-block" onclick="location.href='/fcuser/logout/'">로그아웃</button>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <table class="table table-light">
      <thead class="thead-light">
        <tr>
          <th>#</th>
          <th>제목</th>
          <th>아이디</th>
          <th>일시</th>
        </tr>
      </thead>
      <tbody class="text-dark">
        {% for board in boards %}
        <tr onclick="location.href='/board/detail/{{ board.id }}/'">
          <th>{{ board.id }}</th>
          <td>{{ board.title }}</td>
          <td>{{ board.writer }}</td>
          <td>{{ board.registered_dttm }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="row mt-2">
  <div class="col-12">
    <nav>
      <ul class="pagination justify-content-center">
        {% if boards.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?p={{ boards.previous_page_number }}">이전으로</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">이전으로</a>
        </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ boards.number }} / {{ boards.paginator.num_pages }}</a>
        </li>
        {% if boards.has_next %}
        <li class="page-item">
          <a class="page-link" href="?p={{ boards.next_page_number }}">다음으로</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#">다음으로</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <button class="btn btn-primary" onclick="location.href='/board/write/'">글쓰기</button>
    <button type="button" class="btn btn-primary" onclick="location.href='/'">돌아가기</button>
  </div>
</div>
{% endblock %}

test_community/board/templates/board_write.html
{% extends "base.html" %}
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
  $(document).ready(function () {
    $('#id_writecontents').summernote({
      height: 400
    });
  });
</script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12">
    {% autoescape on %}
    <form method="POST" action=".">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {% autoescape on %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field.field.widget.name }}
        {% if field.name == 'writecontents' %}
        <textarea class="form-control" name="{{ field.name }}" placeholder="{{ field.label }}"
          id="{{ field.id_for_label }}"></textarea>
        {% else %}
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}" />
        {% endif %}
        {% endautoescape %}
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <button type="submit" class="btn btn-primary">저장</button>
      <button type="button" class="btn btn-primary" onclick="location.href='/board/list/'">돌아가기</button>
    </form>
    {% endautoescape %}
  </div>
</div>
{% endblock %}